<Accounts>:
    name: "accounts"
    AnchorLayout:
        anchor_x: "center"
        anchor_y: 'bottom'
        padding: ('30dp', '30dp', '30dp', '30dp')
        MDRaisedButton:
            text: 'Print Record'
    MDTopAppBar:
        title: "CKURE - REGISTERED ACCOUNTS"
        elevation: 0
        pos_hint: {"top": 1}
        md_bg_color:(0/255, 139/255, 199/255)
        left_action_items:[["arrow-left", lambda x : app.back(self.icon)]]
